server:
  servlet:
    context-path: /
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 20MB

  application:
    name: test
  datasource:
    url:
    username:
    password:
    driver-class-name:
    type:
    hikari:
      pool-name:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 5000
      validation-timeout: 5000
      connection-test-query:
      transaction-isolation:
  redis:
    port: 9876
    host: localhost
    jedis:
      pool:
        max-idle: 5
        max-active: 5
        min-idle: 5
        max-wait: 5
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
    password:


logging:
  config: classpath:logback/logback.xml
  level:
    ROOT: debug
  path: /data/logs/test

application:
  exclude-request-urls: [

  ]